<?php

namespace Database\Seeders;

use App\Models\BarangMasuk;
use App\Models\BarangMasukAir;
use App\Models\Transaksi;
use Illuminate\Database\Seeder;

class BarangMasukAirSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Transaksi::insert([
            [
                'kode_transaksi' => 'IDzd3mBEauEB7NN61t0',
                'kode' => 'KBM-01',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-7',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3maB1EuEB7NN6t0',
                'kode' => 'KBM-02',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-08',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEu2EB7NN6t0',
                'kode' => 'KBM-03',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-11',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3amBEuE2B7NN6t0',
                'kode' => 'KBM-04',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-12',
                'bukti_transaksi' => 'eaa19a0e73e8730520577d770e66f23b.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBaEuE3B7NN6t0',
                'kode' => 'KBM-05',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-06',
                'bukti_transaksi' => 'd5d94650c7749065185e4616aed62587.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mB1EuEB7NN6t0',
                'kode' => 'KBM-06',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-12',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuaE3B7NN6t0',
                'kode' => 'KBM-07',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-28',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEtuEB7mNN6t0',
                'kode' => 'KBM-08',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-08',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEBt7aaNN6t0',
                'kode' => 'KBM-09',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-12',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEsuEB7NN6t0',
                'kode' => 'KBM-010',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-21',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuafEB7NN6t0',
                'kode' => 'KBM-011',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-30',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEafB7NN6t0',
                'kode' => 'KBM-012',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-24',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mavsB7NN6t0',
                'kode' => 'KBM-013',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-29',
                'bukti_transaksi' => '64a5195884a79bfe642c44b9095c15d7.jpg',
                'keterangan' => 'Keterangan',
            ],
            // Barang Masuk Air  id Transaksi 13
            [
                'kode_transaksi' => 'IDzd3mBaffn7NN6t0',
                'kode' => 'KBMA-01',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-7',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEBlg9',
                'kode' => 'KBMA-02',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-08',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7Nslnt0',
                'kode' => 'KBMA-03',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-11',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7Nsn390',
                'kode' => 'KBMA-04',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-12',
                'bukti_transaksi' => 'eaa19a0e73e8730520577d770e66f23b.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEssg5NN6t0',
                'kode' => 'KBMA-05',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-01-13',
                'bukti_transaksi' => 'd5d94650c7749065185e4616aed62587.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7NNspn6t0',
                'kode' => 'KBMA-06',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-7',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEskglnN6t0',
                'kode' => 'KBMA-07',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-08',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEusvsdNN6t0',
                'kode' => 'KBMA-08',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-11',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEsfsNN6t0',
                'kode' => 'KBMA-09',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-12',
                'bukti_transaksi' => 'eaa19a0e73e8730520577d770e66f23b.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7NN6t0',
                'kode' => 'KBMA-010',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-02-13',
                'bukti_transaksi' => 'd5d94650c7749065185e4616aed62587.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuErsgN6t0',
                'kode' => 'KBMA-011',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-7',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEsfsN6t0',
                'kode' => 'KBMA-012',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-08',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7df6t0',
                'kode' => 'KBMA-013',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-11',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEBsfe6t0',
                'kode' => 'KBMA-014',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-12',
                'bukti_transaksi' => 'eaa19a0e73e8730520577d770e66f23b.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEB7sfsN6t0',
                'kode' => 'KBMA-015',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-03-13',
                'bukti_transaksi' => 'd5d94650c7749065185e4616aed62587.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEsrrNN6t0',
                'kode' => 'KBMA-016',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-7',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBaskjB7NN6t0',
                'kode' => 'KBMA-017',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-08',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBElsln97NN6t0',
                'kode' => 'KBMA-018',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-11',
                'bukti_transaksi' => '8dc595cd8ff081f53c61ceccb22ae681.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEuEBlkgobjt0',
                'kode' => 'KBMA-019',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-12',
                'bukti_transaksi' => 'eaa19a0e73e8730520577d770e66f23b.jpg',
                'keterangan' => 'Keterangan',
            ],
            [
                'kode_transaksi' => 'IDzd3mBEusosgogN6t0',
                'kode' => 'KBMA-020',
                'metode' => 'BANK BRI',
                'tgl_transaksi' => '2022-04-13',
                'bukti_transaksi' => 'd5d94650c7749065185e4616aed62587.jpg',
                'keterangan' => 'Keterangan',
            ],
        ]);
        BarangMasuk::insert([
            [
                'kode_barang_masuk' => 'KBM-01',
                'bahan' => '1',
                'bahan_baku_id' => '1',
                'supplier_id' => '1',
                'jumlah_pembelian' => '19000',
                'harga' => '3200',
                'sub_total' => '60800000',
                'tgl_masuk' => '2022-01-7',
                'transaksi_id' => '1',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-02',
                'bahan' => '4',
                'bahan_baku_id' => '2',
                'supplier_id' => '2',
                'jumlah_pembelian' => '220',
                'harga' => '225000',
                'sub_total' => '49500000',
                'tgl_masuk' => '2022-01-08',
                'transaksi_id' => '2',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-03',
                'bahan' => '3',
                'bahan_baku_id' => '3',
                'supplier_id' => '3',
                'jumlah_pembelian' => '25',
                'harga' => '375000',
                'sub_total' => '9375000',
                'tgl_masuk' => '2022-01-11',
                'transaksi_id' => '3',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-04',
                'bahan' => '2',
                'bahan_baku_id' => '4',
                'supplier_id' => '3',
                'jumlah_pembelian' => '40',
                'harga' => '70000',
                'sub_total' => '2800000',
                'tgl_masuk' => '2022-01-12',
                'transaksi_id' => '4',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-05',
                'bahan' => '2',
                'bahan_baku_id' => '4',
                'supplier_id' => '3',
                'jumlah_pembelian' => '40',
                'harga' => '70000',
                'sub_total' => '2800000',
                'tgl_masuk' => '2022-02-06',
                'transaksi_id' => '5',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-06',
                'bahan' => '3',
                'bahan_baku_id' => '3',
                'supplier_id' => '3',
                'jumlah_pembelian' => '50',
                'harga' => '70000',
                'sub_total' => '3500000',
                'tgl_masuk' => '2022-02-12',
                'transaksi_id' => '6',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-07',
                'bahan' => '4',
                'bahan_baku_id' => '2',
                'supplier_id' => '2',
                'jumlah_pembelian' => '220',
                'harga' => '225000',
                'sub_total' => '49500000',
                'tgl_masuk' => '2022-02-28',
                'transaksi_id' => '7',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-08',
                'bahan' => '2',
                'bahan_baku_id' => '4',
                'supplier_id' => '3',
                'jumlah_pembelian' => '40',
                'harga' => '70000',
                'sub_total' => '2800000',
                'tgl_masuk' => '2022-03-12',
                'transaksi_id' => '8',
                'status' => 'Selesai',
            ],[
                'kode_barang_masuk' => 'KBM-09',
                'bahan' => '3',
                'bahan_baku_id' => '3',
                'supplier_id' => '3',
                'jumlah_pembelian' => '50',
                'harga' => '70000',
                'sub_total' => '3500000',
                'tgl_masuk' => '2022-03-12',
                'transaksi_id' => '9',
                'status' => 'Selesai',
            ],[
                'kode_barang_masuk' => 'KBM-010',
                'bahan' => '1',
                'bahan_baku_id' => '1',
                'supplier_id' => '1',
                'jumlah_pembelian' => '19000',
                'harga' => '3200',
                'sub_total' => '60800000',
                'tgl_masuk' => '2022-03-21',
                'transaksi_id' => '10',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-011',
                'bahan' => '2',
                'bahan_baku_id' => '4',
                'supplier_id' => '3',
                'jumlah_pembelian' => '40',
                'harga' => '70000',
                'sub_total' => '2800000',
                'tgl_masuk' => '2022-03-30',
                'transaksi_id' => '11',
                'status' => 'Selesai',
            ],[
                'kode_barang_masuk' => 'KBM-012',
                'bahan' => '2',
                'bahan_baku_id' => '4',
                'supplier_id' => '3',
                'jumlah_pembelian' => '40',
                'harga' => '70000',
                'sub_total' => '2800000',
                'tgl_masuk' => '2022-04-24',
                'transaksi_id' => '12',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBM-013',
                'bahan' => '3',
                'bahan_baku_id' => '3',
                'supplier_id' => '3',
                'jumlah_pembelian' => '50',
                'harga' => '70000',
                'sub_total' => '3500000',
                'tgl_masuk' => '2022-04-29',
                'transaksi_id' => '13',
                'status' => 'Selesai',
            ],

        ]);

        BarangMasukAir::insert([
            [
                'kode_barang_masuk' => 'KBMA-01',
                'bahan' => '1',
                'bahan_baku_air_id' => '1',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '25000',
                'sub_total' => '12500000',
                'tgl_masuk' => '2022-01-07',
                'transaksi_id' => '14',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-02',
                'bahan' => '2',
                'bahan_baku_air' => '2',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-01-08',
                'transaksi_id' => '15',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-03',
                'bahan' => '3',
                'bahan_baku_air' => '3',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-01-11',
                'transaksi_id' => '16',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-04',
                'bahan' => '4',
                'bahan_baku_air' => '4',
                'supplier_id' => '6',
                'jumlah_pembelian' => '500',
                'harga' => '19000',
                'sub_total' => '9500000',
                'tgl_masuk' => '2022-01-12',
                'transaksi_id' => '17',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-05',
                'bahan' => '5',
                'bahan_baku_air' => '5',
                'supplier_id' => '7',
                'jumlah_pembelian' => '500',
                'harga' => '16000',
                'sub_total' => '8000000',
                'tgl_masuk' => '2022-01-13',
                'transaksi_id' => '18',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-06',
                'bahan' => '1',
                'bahan_baku_air' => '1',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '25000',
                'sub_total' => '12500000',
                'tgl_masuk' => '2022-02-07',
                'transaksi_id' => '19',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-07',
                'bahan' => '2',
                'bahan_baku_air' => '2',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-02-08',
                'transaksi_id' => '20',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-08',
                'bahan' => '3',
                'bahan_baku_air' => '3',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-02-11',
                'transaksi_id' => '21',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-09',
                'bahan' => '4',
                'bahan_baku_air' => '4',
                'supplier_id' => '6',
                'jumlah_pembelian' => '500',
                'harga' => '19000',
                'sub_total' => '9500000',
                'tgl_masuk' => '2022-02-12',
                'transaksi_id' => '22',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-010',
                'bahan' => '5',
                'bahan_baku_air' => '5',
                'supplier_id' => '7',
                'jumlah_pembelian' => '500',
                'harga' => '16000',
                'sub_total' => '8000000',
                'tgl_masuk' => '2022-02-13',
                'transaksi_id' => '23',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-011',
                'bahan' => '1',
                'bahan_baku_air' => '1',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '25000',
                'sub_total' => '12500000',
                'tgl_masuk' => '2022-03-07',
                'transaksi_id' => '24',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-012',
                'bahan' => '2',
                'bahan_baku_air' => '2',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-03-08',
                'transaksi_id' => '25',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-013',
                'bahan' => '3',
                'bahan_baku_air' => '3',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-03-11',
                'transaksi_id' => '26',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-014',
                'bahan' => '4',
                'bahan_baku_air' => '4',
                'supplier_id' => '6',
                'jumlah_pembelian' => '500',
                'harga' => '19000',
                'sub_total' => '9500000',
                'tgl_masuk' => '2022-03-12',
                'transaksi_id' => '27',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-015',
                'bahan' => '5',
                'bahan_baku_air' => '5',
                'supplier_id' => '7',
                'jumlah_pembelian' => '500',
                'harga' => '16000',
                'sub_total' => '8000000',
                'tgl_masuk' => '2022-03-13',
                'transaksi_id' => '28',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-016',
                'bahan' => '1',
                'bahan_baku_air' => '1',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '25000',
                'sub_total' => '12500000',
                'tgl_masuk' => '2022-04-07',
                'transaksi_id' => '29',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-017',
                'bahan' => '2',
                'bahan_baku_air' => '2',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-04-08',
                'transaksi_id' => '30',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-018',
                'bahan' => '3',
                'bahan_baku_air' => '3',
                'supplier_id' => '5',
                'jumlah_pembelian' => '500',
                'harga' => '10000',
                'sub_total' => '5000000',
                'tgl_masuk' => '2022-04-11',
                'transaksi_id' => '31',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-019',
                'bahan' => '4',
                'bahan_baku_air' => '4',
                'supplier_id' => '6',
                'jumlah_pembelian' => '500',
                'harga' => '19000',
                'sub_total' => '9500000',
                'tgl_masuk' => '2022-04-12',
                'transaksi_id' => '32',
                'status' => 'Selesai',
            ],
            [
                'kode_barang_masuk' => 'KBMA-20',
                'bahan' => '5',
                'bahan_baku_air' => '5',
                'supplier_id' => '7',
                'jumlah_pembelian' => '500',
                'harga' => '16000',
                'sub_total' => '8000000',
                'tgl_masuk' => '2022-04-13',
                'transaksi_id' => '33',
                'status' => 'Selesai',
            ],
        ]);
    }
}
